### ISSUE TITLE
Maximum call stack size exceeded - mail with file more than 100ko ...

### ISSUE THREAD

**Issue by andrelec1** [emailjs/emailjs-mime-parser#50]
I have a script that run every hours ...
This script connect to a email address, for getting csv from mail ...
When i write my script, I only receive small file ( 50  - 100 ko ) and my script work perfectly ... 
Now we have another automate that send email, but the file is more like 150 - 200ko ...

When i send the body[] in emailjs-mime-parser i have a :
```
(node:14727) UnhandledPromiseRejectionWarning: RangeError: Maximum call stack size exceeded
    at apply (/home/andrelec1/Projects/data_harvester/node_modules/emailjs-mime-codec/src/charset.js:11:51)
    at base64Decode (/home/andrelec1/Projects/data_harvester/node_modules/emailjs-mime-codec/src/mimecodec.js:87:37)
    at MimeNode._decodeBodyBuffer (/home/andrelec1/Projects/data_harvester/node_modules/emailjs-mime-parser/src/mimeparser.js:77:28)
    at MimeNode._decodeBodyBuffer [as _emitBody] (/home/andrelec1/Projects/data_harvester/node_modules/emailjs-mime-parser/src/mimeparser.js:345:10)
    at MimeNode._emitBody [as finalize] (/home/andrelec1/Projects/data_harvester/node_modules/emailjs-mime-parser/src/mimeparser.js:66:12)
...
``` 
My code : 
```js
import ImapClient from 'emailjs-imap-client';
import ImapParse from 'emailjs-mime-parser';
import jethro from 'jethro';
import _ from 'lodash';
import { fileSaver } from './fileSaver';

class MailClient {
  #client = null;
  
  constructor(url, port, params) {
    this.#client = new ImapClient(url, port, params);
    this.#client.onerror = this.onError;
    this.crawl();
  };

  onError = (error) => {
    jethro.error('ImapClient', error);
  };

  crawl = () => {
    this.#client.connect().then(this.connect);
  };

  connect = async () => {
    jethro.success('ImapClient', 'Connexion opened success.');
    this.#client.selectMailbox('INBOX').then(this.selectMailBox);
  };

  selectMailBox = async () => {
    jethro.success('ImapClient', 'Open INBOX');
    await this.#client.listMessages('INBOX', '1:*', ['uid', 'flags', 'body', 'body[]', 'envelope', 'bodystructure'])
      .then(this.listMessages)
      .then(this.logout)
    ;
  };

  listMessages = async (mails) => {
    return new Promise(resolve => {
      jethro.success('ImapClient', 'Read all messages in INBOX');
      jethro.success('ImapClient', `${mails.length} mails found.`);

      const mailsPromises = mails.reduce((promiseChain, mail) => {
        return promiseChain.then(async () => {
          jethro.info('ImapClient', `Mail ${mail.uid} extracting`);
          await this.extractData(mail);
          jethro.info('ImapClient', `Mail ${mail.uid} extracted`);
          await this.deleteMail(mail);
          jethro.info('ImapClient', `Mail ${mail.uid} delete`);
        });
      }, Promise.resolve());

      mailsPromises.then(() => {
        resolve();
      });
    });
  };

  extractData = async (mail) => {
    return new Promise(resolve => {
      const parsedMail = ImapParse(mail['body[]']);

      const from = _.find(_.find(parsedMail.headers.from).value).address;
      const fileNode = this.findNodeWithAttachment(parsedMail.childNodes);
      this.saveFile(from, fileNode).then(resolve).catch(() => {
        jethro.error('FileSave', 'error when file is saved to the disk');
      });
    });
  };

  deleteMail = async (mail) => {
    return new Promise(resolve => {
      //this.#client.deleteMessages('INBOX', `${mail.uid}`, { byUid: true }).then(() => {
      jethro.warning('ImapClient', `Mail UID : ${mail.uid} is delete.`);
      resolve();
      //});
    });
  };

  findNodeWithAttachment = (childNodes) => {
    return _.find(childNodes, (childNode) => {
      const potentialNodeContentType = _.find(childNode.headers['content-type']).value;
      const potentialNodeDisposition = _.find(childNode.headers['content-disposition']);
      return ['text/csv', 'application/octet-stream'].includes(potentialNodeContentType) &&
        potentialNodeDisposition.value === 'attachment' &&
        potentialNodeDisposition.params.filename.endsWith('.csv');
    });
  };

  saveFile = (email, fileNode) => {
    return new Promise(resolve => {
      if (fileNode === undefined) {
        jethro.warning('ImapClient', `${email} send mail without csv valid file.`);
        resolve();
      }

      const [folderName] = email.split('@');
      const fileName = _.find(fileNode.headers['content-type']).params.name;
      const data = fileNode.content;
      fileSaver.save(folderName, fileName, data).then(resolve);
    });
  };

  logout = () => {
    this.#client.logout().then(() => {
      jethro.success('ImapClient', 'Logout success.');
      this.close();
    });
  };

  close = () => {
    this.#client.close().then(() => {
      jethro.success('ImapClient', 'Connexion closed success');
    });
  };
}

export default MailClient;
```
Error in 'extractData()'

**Comment by andrelec1** [comment]
OK, i just found, and it work !
https://www.npmjs.com/package/emailjs-mime-parser-bigattachments

but why  ? O_o
